bot_token: "ABCDEFGHIJKLMNOPQRSTUVWXYZ124"

chat_channel_id: "12345678901234567890"

admin_role_id: "1234567891234567890"

# Sets the "Playing ..." message
playing_message: "Mindustry"

# Supports colors, available placeholders : [<rolecolor><playername>, <message>]
# Role color currently doesnt work!
# Note: doing something like "[[gray]" will escape the color. to avoid that,
# add an invisible character between "[["
discord_to_mindustry_chat_format: "[‎[gray][Discord] <rolecolor><playername>[white]] <message>"

# Does not support colors, available placeholders: [<playername>, <message>]
mindustry_to_discord_chat_format: "<playername> >> <message>"